const std = @import("std");

/// 词法单元（token）。`Token` 只存种类与起止字节偏移，不复制源码文本；
/// 文本经 `tree.tokenSlice(index)` 按偏移回源取得，词法阶段对字面量零拷贝。
/// 偏移均为源码内的绝对字节下标（`ByteOffset`）。
pub const Token = struct {
    /// 源码内的字节偏移类型。词法阶段直接以下标赋值，故用 `usize`。
    pub const ByteOffset = usize;

    /// 所有词法种类的扁平枚举，与 PHP 官方 `zend_language_scanner` 对应。
    /// 单点定义，解析器与 AST 只引用、不重复。
    pub const Tag = enum {
        eof,
        invalid,

        // 字面量
        int_literal,
        float_literal,
        string_literal,

        // 字符串插值（双引号 / heredoc 的内部分词）
        string_start,
        string_end,
        string_part,

        // 名称
        identifier,
        variable,
        magic_const,

        // 标记（tag）
        open_tag,
        close_tag,
        comment,
        doc_comment,

        // 标点
        comma,
        semicolon,
        colon,
        at,
        arrow,
        double_colon,
        lparen,
        rparen,
        lbrace,
        rbrace,
        lbracket,
        rbracket,
        hash,
        ellipsis,
        backslash,

        // 运算符
        equals,
        plus,
        minus,
        asterisk,
        slash,
        percent,
        dot,
        bang,
        tilde,
        ampersand,
        pipe,
        double_arrow,
        question,
        double_plus,
        double_minus,
        double_asterisk,
        equal_equal,
        bang_equal,
        equal_equal_equal,
        bang_equal_equal,
        less_than,
        greater_than,
        less_equal,
        greater_equal,
        bool_and,
        bool_or,
        plus_equal,
        minus_equal,
        asterisk_equal,
        slash_equal,
        percent_equal,
        dot_equal,
        double_asterisk_equal,
        ampersand_equal,
        pipe_equal,
        tilde_equal,
        left_shift,
        right_shift,
        left_shift_equal,
        right_shift_equal,
        null_coalesce,
        nullsafe_arrow,
        caret,
        caret_equal,
        backtick,

        // 关键字
        kw_if,
        kw_else,
        kw_elseif,
        kw_while,
        kw_for,
        kw_foreach,
        kw_as,
        kw_function,
        kw_class,
        kw_extends,
        kw_implements,
        kw_return,
        kw_echo,
        kw_namespace,
        kw_new,
        kw_true,
        kw_false,
        kw_null,
        kw_public,
        kw_protected,
        kw_private,
        kw_static,
        kw_var,
        kw_const,
        kw_abstract,
        kw_final,
        kw_enum,
        kw_interface,
        kw_trait,
        kw_match,
        kw_readonly,
        kw_default,
        kw_instanceof,
        kw_and,
        kw_or,
        kw_xor,
        kw_fn,
        kw_clone,
        kw_print,
        kw_yield,
        kw_include,
        kw_include_once,
        kw_require,
        kw_require_once,
        kw_list,
        kw_isset,
        kw_empty,
        kw_eval,
        kw_exit,
        kw_die,
        kw_throw,
        kw_use,
        kw_do,
        kw_break,
        kw_continue,
        kw_switch,
        kw_case,
        kw_try,
        kw_catch,
        kw_finally,
        kw_declare,
        kw_goto,
        kw_global,
        kw_unset,
        kw_insteadof,
        kw_halt_compiler,
        inline_html,
    };

    /// 词法序列的存储结构。`MultiArrayList` 把 `tag`/`start`/`end` 分列存放（SoA）。
    pub const TokenList = std.MultiArrayList(struct {
        tag: Tag,
        start: ByteOffset,
        end: ByteOffset,
    });

    /// 返回某个词法种类固定对应的字面文本（如 `;` → `";"`）。
    /// 仅对标点/运算符有效；标识符、字面量等需经源码切片取得，故返回 `null`。
    ///
    /// ```zig
    /// try std.testing.expect(std.meta.eql(Token.lexeme(.arrow).?, "->"));
    /// ```
    pub fn lexeme(tag: Tag) ?[]const u8 {
        return switch (tag) {
            .comma => ",",
            .semicolon => ";",
            .colon => ":",
            .at => "@",
            .arrow => "->",
            .double_colon => "::",
            .lparen => "(",
            .rparen => ")",
            .lbrace => "{",
            .rbrace => "}",
            .lbracket => "[",
            .rbracket => "]",
            .hash => "#",
            .ellipsis => "...",
            .backslash => "\\",
            .equals => "=",
            .plus => "+",
            .minus => "-",
            .asterisk => "*",
            .slash => "/",
            .percent => "%",
            .dot => ".",
            .bang => "!",
            .tilde => "~",
            .ampersand => "&",
            .pipe => "|",
            .double_arrow => "=>",
            .question => "?",
            .double_plus => "++",
            .double_minus => "--",
            .double_asterisk => "**",
            .equal_equal => "==",
            .bang_equal => "!=",
            .equal_equal_equal => "===",
            .bang_equal_equal => "!==",
            .less_than => "<",
            .greater_than => ">",
            .less_equal => "<=",
            .greater_equal => ">=",
            .bool_and => "&&",
            .bool_or => "||",
            .plus_equal => "+=",
            .minus_equal => "-=",
            .asterisk_equal => "*=",
            .slash_equal => "/=",
            .percent_equal => "%=",
            .dot_equal => ".=",
            .double_asterisk_equal => "**=",
            .ampersand_equal => "&=",
            .pipe_equal => "|=",
            .caret_equal => "^=",
            .left_shift => "<<",
            .right_shift => ">>",
            .left_shift_equal => "<<=",
            .right_shift_equal => ">>=",
            .null_coalesce => "??",
            .nullsafe_arrow => "?->",
            .caret => "^",
            .caret_equal => "^=",
            .backtick => "`",
            else => null,
        };
    }

    /// 判断词法种类是否为注释。注释不进节点，但作为 token 保留在 `Ast.tokens`，
    /// 下游经 `Ast.docCommentBefore` 取回 docblock。
    pub fn isComment(tag: Tag) bool {
        return tag == .comment or tag == .doc_comment;
    }
};
